package com.saishaddai.flashcards.model.fcdata

import com.saishaddai.flashcards.model.Flashcard

val databaseCards = listOf(
    // Jetpack Room (Android)
    Flashcard(7, 701, "What is Jetpack Room?", "A persistence library that provides an abstraction layer over SQLite to allow fluent database access while leveraging its full power."),
    Flashcard(7, 702, "What does @Entity do in Room?", "It defines a class as a database table where each field represents a column."),
    Flashcard(7, 703, "What is the purpose of @Dao in Room?", "Data Access Object: an interface or abstract class containing methods used for accessing the database."),
    Flashcard(7, 704, "What is @Database in Room?", "An annotation for the main access point class that holds the database and serves as the connection to your app's persisted data."),
    Flashcard(7, 705, "What are Room TypeConverters?", "Methods that allow you to persist custom data types (like Date) by converting them to a type Room knows how to store."),
    Flashcard(7, 706, "What is @Insert(onConflict) for?", "It specifies the strategy to use when a conflict occurs during insertion, such as OnConflictStrategy.REPLACE."),
    Flashcard(7, 707, "What does @Query do?", "It allows you to write raw SQL queries for DAO methods, which are verified at compile-time by Room."),
    Flashcard(7, 708, "How does Room support reactive UI?", "By returning observable types like Flow, LiveData, or RxJava from DAO methods."),
    Flashcard(7, 709, "What are Room Migrations?", "Classes that define how to transition the database schema from one version to another while preserving user data."),
    Flashcard(7, 710, "What is @Relation used for?", "It is used in POJOs to automatically fetch related entities in one-to-many or many-to-many relationships."),
    Flashcard(7, 711, "What does @Embedded do?", "It allows you to use a nested object as a field within an Entity, flattening its fields into the table."),
    Flashcard(7, 712, "Why shouldn't you access Room on the main thread?", "To avoid UI stutters or ANR (Application Not Responding) errors; Room enforces this for synchronous queries."),
    Flashcard(7, 713, "What is @Transaction in Room?", "An annotation that ensures multiple database operations are executed as a single atomic unit."),
    Flashcard(7, 714, "What is an In-memory database in Room?", "A database created via Room.inMemoryDatabaseBuilder that resides in RAM and is lost when the app process dies."),
    Flashcard(7, 715, "What is Room Auto-migration?", "A feature introduced in Room 2.4.0 that can automatically generate migration code for simple schema changes."),
    Flashcard(7, 716, "What is @PrimaryKey(autoGenerate = true)?", "It tells Room to automatically assign unique IDs to new records."),
    Flashcard(7, 717, "What is @Ignore used for?", "It tells Room to ignore a specific field in an Entity or a method in a DAO."),
    Flashcard(7, 718, "How to pre-populate a Room database?", "By using .createFromAsset() or .createFromFile() when building the database instance."),
    Flashcard(7, 719, "What is exportSchema in @Database?", "A property that, when true, exports the database schema to a JSON file for version history and testing."),
    Flashcard(7, 720, "What is the benefit of Room over raw SQLite?", "Compile-time SQL verification, reduced boilerplate, and easy integration with modern reactive components."),
    Flashcard(7, 721, "What is @ColumnInfo?", "An annotation used to customize the column name or properties in the database table."),
    Flashcard(7, 722, "Can Room return a PagingSource?", "Yes, Room integrates with the Paging library to handle large data sets efficiently."),
    Flashcard(7, 723, "What is KSP in Room?", "Kotlin Symbol Processing, a faster alternative to KAPT for Room's code generation."),
    Flashcard(7, 724, "What is Multi-instance Invalidation?", "A Room feature that keeps multiple database instances in sync across different processes."),
    Flashcard(7, 725, "How do you handle Many-to-Many in Room?", "By using an associative entity (junction table) and @Relation with an 'associateBy' parameter."),

    // SQLDelight & KMP & SQL
    Flashcard(7, 726, "What is SQLDelight?", "A library that generates typesafe Kotlin APIs from SQL statements, widely used in Kotlin Multiplatform (KMP)."),
    Flashcard(7, 727, "What are .sq files in SQLDelight?", "Files where you write raw SQL schema and queries, from which SQLDelight generates Kotlin code."),
    Flashcard(7, 728, "What are SQLDelight Drivers?", "Platform-specific implementations (e.g., AndroidSqliteDriver, NativeSqliteDriver) that open database connections."),
    Flashcard(7, 729, "SQLDelight vs Room?", "SQLDelight is SQL-first (code from SQL), while Room is code-first (SQL from annotations/mapping)."),
    Flashcard(7, 730, "Why is SQLDelight popular for KMP?", "Because it has no dependency on the Android runtime and works on iOS, Desktop, and Web."),
    Flashcard(7, 731, "What are SQLDelight Column Adapters?", "Used to map custom Kotlin types (like Enums) to types that SQLDelight knows how to store."),
    Flashcard(7, 732, "How are SQLDelight migrations managed?", "Via .sqm files or by naming .sq files with version numbers to define schema updates."),
    Flashcard(7, 733, "What is 'expect/actual' in KMP database setup?", "A pattern used to provide the correct SQLDelight driver for each target platform."),
    Flashcard(7, 734, "What is a SQL Primary Key?", "A constraint that uniquely identifies each record in a table and cannot contain null values."),
    Flashcard(7, 735, "What is a SQL Foreign Key?", "A field that links a column in one table to the primary key of another table, ensuring referential integrity."),
    Flashcard(7, 736, "What is a SQL Index?", "A database object used to speed up data retrieval operations, though it can slow down writes."),
    Flashcard(7, 737, "What is an INNER JOIN?", "A SQL join that returns records that have matching values in both tables."),
    Flashcard(7, 738, "What is a LEFT JOIN?", "A SQL join that returns all records from the left table and matching records from the right table."),
    Flashcard(7, 739, "What are ACID properties?", "Atomicity, Consistency, Isolation, and Durability - properties that guarantee reliable database transactions."),
    Flashcard(7, 740, "What is SQL Normalization?", "The process of organizing data to reduce redundancy and improve data integrity."),
    Flashcard(7, 741, "What is SQLite WAL Mode?", "Write-Ahead Logging, which improves concurrency by allowing readers and writers to operate simultaneously."),
    Flashcard(7, 742, "Best Practice: Naming Conventions?", "Use snake_case for tables and columns (e.g., user_profile) for broader compatibility."),
    Flashcard(7, 743, "Best Practice: Large Data?", "Avoid storing large images or blobs in the database; store the file path instead."),
    Flashcard(7, 744, "What is SQL Injection?", "A security vulnerability where an attacker can interfere with queries; use bind parameters to prevent it."),
    Flashcard(7, 745, "How to handle database versions?", "Always increment the version number and provide migration paths to prevent app crashes."),
    Flashcard(7, 746, "What is a UNIQUE constraint?", "Ensures that all values in a column are distinct from each other."),
    Flashcard(7, 747, "What is GROUP BY in SQL?", "A statement used to group rows that have the same values into summary rows."),
    Flashcard(7, 748, "What is a SQL View?", "A virtual table based on the result-set of an SQL statement."),
    Flashcard(7, 749, "What is the 'EXPLAIN QUERY PLAN' command?", "Used in SQLite to describe how a query will be executed, helping in performance optimization."),
    Flashcard(7, 750, "What is the 'VACUUM' command?", "A SQL command that rebuilds the database file, repacking it into a minimal amount of disk space.")
)
