package com.saishaddai.flashcards.model

data class Flashcard(val deckId: Int,
                     val id: Int,
                     val question: String,
                     val answer: String,
                     val discovered: Boolean = false
)

val flashcards = listOf(
    //OOP
    Flashcard(1, 1, "What is a class?", "A blueprint for creating objects", false),
    Flashcard(1, 2, "What is an object?", "An instance of a class", false),
    Flashcard(1, 3, "What is an interface?", "A contract with methods without implementations", false),
    Flashcard(1, 4, "What is an abstract class?", "A base class with partial implementations", false),
    Flashcard(1, 5, "Tell me the four pillars of OOP", "Encapsulation, Inheritance, Polymorphism, Abstraction", false),
    Flashcard(1, 6, "What is Encapsulation?", "Hide internal state of a class, control access to it", false),
    Flashcard(1, 7, "Whats is Abstraction?", "Simplify use of a class exposing only the information that matters", false),
    Flashcard(1, 8, "What is Polymorphism?", "Same method, different behavior", false),
    Flashcard(1, 9, "What is Inheritance?", "Reuse code via Parent-Child relationship", false),
    Flashcard(1, 10, "In classes relationships, what is Association?", "General link between classes", false),
    Flashcard(1, 11, "In classes relationships, what is Aggregation?", "Whole part relationship, parts can exist independently. Example: Library - Book (books can exists outside the library)", false),
    Flashcard(1, 12, "In classes relationships, what is Composition?", "String whole part relationship. Parts die with the whole. Example House - Room (rooms aare parte of a house and nowhere else)", false),
    Flashcard(1, 13, "In classes relationships, what is Dependency?", "One class uses another temporarily. Example: Car - Mechanic (car depends on mechanic for service", false),
    Flashcard(1, 14, "In classes relationships, what is Realization?", "Class implements interface. Example: Bird implements Flyable", false),
    Flashcard(1, 15, "What are Unidirectional relationships?", "One-way relationship. Example Order - Customer (order knows customer but no vice versa", false),
    Flashcard(1, 16, "What are Bidirectional relationships?", "Two-way relationship. Example Husband - Wife (both knows each other", false),
    Flashcard(1, 17, "What are the OOP Pitfalls?", "Overuse of inheritance, tight coupling, poor encapsulation, violate SOLID principles", false),
    Flashcard(1, 18, "What the S means in SOLID principles?", "Every class has only one single responsibility and no more", false),
    Flashcard(1, 19, "What the O means in SOLID principles?", "Open to extension, close to modification", false),
    Flashcard(1, 20, "What the L means in SOLID principles?", "Liskov Substitution. subclass can be substituted for its base class without affecting the application", false),
    Flashcard(1, 21, "What the I means in SOLID principles?", "Interface Segregation. An interface can't make you implement all the methods in it", false),
    Flashcard(1, 22, "What the D means in SOLID principles?", "Dependency Inversion. A class must depend on abstractions not implementations", false),

    //Android Core
    Flashcard(2, 23, "What are the core building blocks of an Android Application?", "Activities, Fragments, Services, Content Providers, Broadcast Receivers, View"),
    Flashcard(2, 24, "What ia an Activity?", "Represents a single screen with its layout and logic"),
    Flashcard(2, 25, "What is a Fragment?", "Modular piece of UI that can be reused in different places"),
    Flashcard(2, 25, "What is a Service?", "Background processes that run in the background"),
    Flashcard(2, 26, "What is a Content Provider?", ""),
    Flashcard(2, 26, "What is a Broadcast Receiver?", ""),
    Flashcard(2, 26, "What is a View?", ""),
    Flashcard(2, 26, "What is a are Layouts", ""),
    Flashcard(2, 26, "What is the Manifest File", ""),
    Flashcard(2, 26, "What is an Intent", ""),
    Flashcard(2, 26, "What is an Explicit Intent", ""),
    Flashcard(2, 26, "What is an Implicit Intent", ""),
    Flashcard(2, 26, "What is the Android Lifecycle", ""),
    Flashcard(2, 26, "What is an Activity Lifecycle", ""),
    Flashcard(2, 26, "What is an Application Context in Android", ""),
    Flashcard(2, 26, "What is Activity Context in Android", ""),
    Flashcard(2, 26, "What is the Fragment Lifecycle", ""),
    Flashcard(2, 26, "What is the difference between replacing and adding fragments in the backstack?", ""),
    Flashcard(2, 26, "What happens when the device is moved from Portrait mode to Landscape?", ""),
    Flashcard(2, 26, "What does RTL mean in UI Design?", ""),
    Flashcard(2, 26, "What is an Intent Service?", ""),
    Flashcard(2, 26, "What is an Async Task?", ""),
    Flashcard(2, 26, "What is a Thread?", ""),
    Flashcard(2, 26, "What is Parcelable in Android?", ""),
    Flashcard(2, 26, "Serializable vs Parcelable?", ""),
    Flashcard(2, 26, "What is a Handler?", ""),
    Flashcard(2, 26, "What is a StickyIntent?", ""),
    Flashcard(2, 26, "What is a PendingIntent?", ""),
    Flashcard(2, 26, "What are IntentFilters?", ""),
    Flashcard(2, 26, "What are Loaders in Android?", ""),
    Flashcard(2, 26, "What is ConstraintLayout?", ""),
    Flashcard(2, 26, "What is ARN?", ""),
    Flashcard(2, 26, "What is commit() in SharedPreferences?", ""),
    Flashcard(2, 26, "What is apply() in SharedPreferences?", ""),
    Flashcard(2, 26, "How to support different screen sizes?", ""),
    Flashcard(2, 26, "What is RecyclerView?", ""),
    Flashcard(2, 26, "What is the ‘ViewHolderPattern’ in RecyclerView?", ""),
    Flashcard(2, 26, "What is AAPT?", ""),
    Flashcard(2, 26, "What is AIDL?", ""),
    Flashcard(2, 26, "What is ‘JobScheduler’?", ""),
    Flashcard(2, 26, "What are Storage methods?", "Shared preferences, internal storage, external, SQLite"),
    Flashcard(2, 26, "What is ‘WorkManager’?", ""),
    Flashcard(2, 26, "What is the Zygote process?", ""),
    Flashcard(2, 26, "How do Fragments communicate?", "Bundle, View-Model"),
    Flashcard(2, 26, "What is a Binder?", ""),
    Flashcard(2, 26, "What is ‘ANR Watchdog’?", ""),
    Flashcard(2, 26, "What is a Looper?", ""),
    Flashcard(2, 26, "What is a MessageQueue?", ""),
    Flashcard(2, 26, "What is the Main thread in Android?", ""),
    Flashcard(2, 26, "ApplicationContext vs BaseContext?", ""),
    Flashcard(2, 26, "What is a Task in backstack?", ""),
    Flashcard(2, 26, "What is ‘PackageManager’?", ""),
    Flashcard(2, 26, "What is DVM?", ""),
    Flashcard(2, 26, "What is ART?", ""),
    Flashcard(2, 26, "What is the purpose of the file proguard-rules.pro?", ""),
    Flashcard(2, 26, "What are the ‘.dex’ files?", ""),
    Flashcard(2, 26, "What is the Android boot process?", ""),
    Flashcard(2, 26, "What is ‘compile’ in Gradle?", ""),
    Flashcard(2, 26, "What is ‘implementation’ in Gradle?", ""),
    Flashcard(2, 26, "What is ‘api’ in Gradle?", ""),

    Flashcard(2, 26, "What is 'libs.versions.toml‘ in Gradle?", ""),
    Flashcard(2, 26, "What is the difference between build.gradle (Project and Module)?", ""),
    Flashcard(2, 26, "What is versionName and versionCode in Gradle?", ""),
    Flashcard(2, 26, "What are flavors in Gradle?", ""),
    Flashcard(2, 26, "Flavors vs buildTypes?", ""),

    //add more about versions, build gradle, flavors, buildVersions, appTools, etc
    Flashcard(2, 26, "What is a Work Request?", ""),
    Flashcard(2, 26, "What are the result types in WorkManager?", ""),
    Flashcard(2, 26, "Which are the states of a Work in WorkManager?", "enqueued, running, succeeded, failed, blocked, cancelled"),
    Flashcard(2, 26, "Worker vs CoroutineWorker?", ""),
    Flashcard(2, 26, "WorkManager vs JobScheduler?", ""),


    //Kotlin
    Flashcard(3, 8, "3: What is the capital of France?", "Paris", false),
    Flashcard(3, 9, "3: What is the largest planet in our solar system?", "Jupiter", false),
    Flashcard(3, 10, "3: What is the smallest country in the world?", "Vatican City", false),
    Flashcard(3, 11, "3: What is the highest mountain in the world?", "Mount Everest", false),

    //Kotlin MP
    Flashcard(4, 12, "4: What is the capital of France?", "Paris", false),
    Flashcard(4, 13, "4: What is the largest planet in our solar system?", "Jupiter", false),
    Flashcard(4, 14, "4: What is the smallest country in the world?", "Vatican City", false),
    Flashcard(4, 15, "4: What is the highest mountain in the world?", "Mount Everest", false),

)
