name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  RUN_BUILD: true
  RUN_UNIT_TEST: true
  RUN_INSTRUMENTED_TEST: false
  RUN_RELEASE_SIGNING: false
  RUN_TEST_REPORTS: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ env.RUN_BUILD == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ env.RUN_UNIT_TEST == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

  instrumented-test:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ env.RUN_INSTRUMENTED_TEST == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Instrumented Tests
        run: ./gradlew connectedDebugAndroidTest

  release-signing:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ env.RUN_RELEASE_SIGNING == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Sign and Assemble Release
        run: ./gradlew assembleRelease
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

  test-reports:
    runs-on: ubuntu-latest
    needs: unit-test
    if: ${{ env.RUN_TEST_REPORTS == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate Test Reports
        run: ./gradlew jacocoTestReport
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: app/build/reports/tests/testDebugUnitTest
